#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2022

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: Invoke-RestMethod -Uri 'https://dot.net/v1/dotnet-install.ps1' -OutFile '.\dotnet-install.ps1'
  - ps: New-Item -Path .\.dotnet -ItemType Directory -Force | Out-Null
  - ps: .\dotnet-install.ps1 -Channel 6.0 -InstallDir .\.dotnet
  - ps: .\build.ps1 --target=CI

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> recipe.cake
