name: Posix Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Get the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET SDK 5.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Install .NET SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET Core SDK (global.json)
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: Run-Bakery-Integration-Tests
          verbosity: Normal
          cake-version: 0.38.5
          cake-bootstrap: true